---
title: "An치lise Enzim치tica"
author: "Panosso, AR"
date: "2026-01-29"
output: html_document
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  warning = FALSE,
  error = FALSE,
  message = FALSE,
  comment = "#>"
)
```

#### Carregando Pacotes
```{r}
library(tidyverse)
library(agricolae)
library(ExpDes.pt)
```


#### Carregando o Banco de dados
```{r}
data_set <- read_rds("../data/data-set-analise-enzima.rds")
glimpse(data_set)
```

#### An치lise de Vari칙ncia - com teste de pressupostos

```{r}
names_variable <- data_set |> select(sps:ni) |> names()
walk(names_variable, ~{
  data_set_aux <- data_set |> 
    select(c(data:bloco,!!sym(.x))) |> 
    mutate(
      trat = as_factor(trat) 
    ) |> 
    drop_na()

  df_aux <- data_set_aux 
  y <- df_aux  |> pull(!!sym(.x))
  trat <- df_aux  |> pull(trat)
  bloco <- df_aux  |> pull(bloco)
  data <- df_aux  |> pull(data) |> as.character() |> as_factor()
  fator <- interaction(trat,data)
  mod_dbc <- aov(y ~ fator + bloco)
  print(paste("||======= ANOVA para:",.x,"=======||"))
  psub2.dbc(trat,data,bloco,y,mcomp = "tukey",sigF = .1,fac.names = c("Trat","Data"))
  plot_reg <- df_aux |>
    group_by(data,trat) |>
    summarise(
      media = mean(!!sym(.x))
    ) |>
    ggplot(aes(x = data, y = media,color=as_factor(trat))) +
    geom_line() +
    labs(
      y = .x,
      x = "Data",
      color = "Dose"
    ) +
    theme_minimal()
  print(plot_reg)
})

```
