---
title: "Análise Multivariada"
author: "Panosso, AR"
date: "2026-01-29"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  warning = FALSE,
  error = FALSE,
  message = FALSE,
  comment = "#>"
)
```

#### Carregando Pacotes
```{r}
library(tidyverse)
library(agricolae)
library(ExpDes.pt)
library(vegan)
```

#### Carregando o Banco de dados
```{r}
data_set_prod <- read_rds("../data/data-set-producao.rds")
data_set_gas <- read_rds("../data/data-set-trocas-gasosas.rds") |> 
  filter(data == date("2025-04-14"))
data_set_enzi <- read_rds("../data/data-set-analise-enzima.rds") |> 
  filter(data == date("2025-05-06"))
data_set_tecno <- read_rds("../data/data-set-tecnologica.rds") |> 
  group_by(faz,trat,dose,bloco) |> 
  summarise(across(
    .cols = peso:atr,
    .fns = mean,na.rm=TRUE,
    .names = "{.col}"
  )) |> 
  ungroup()
glimpse(data_set_tecno)
glimpse(data_set_prod)
glimpse(data_set_enzi)
glimpse(data_set_gas)

data_set_mult <- left_join(
  data_set_prod |> select(-c(id,data,parcela,rep,tch1:tah6)),
  data_set_tecno,
  by = c("faz","trat","dose","bloco")
) |> 
  left_join(data_set_enzi |> select(-c(id,data,rep,parcela)),
  by = c("faz","trat","dose","bloco")) |> 
  left_join(data_set_gas |> select(-c(id,data,rep,parcela)),
  by = c("faz","trat","dose","bloco")
  ) |> 
  group_by(trat,dose,bloco) |> 
  summarise(across(
    .cols = tch_media:t_foliar,
    .fns = mean,na.rm=TRUE,
    .names = "{.col}")) |>
  ungroup() |> 
  select(-bloco,-dose,-peso,-altura,-e_n)
glimpse(data_set_mult)
```
### Análise de Correlação Linear

```{r}
dfau_cor <- cor(data_set_mult[-1]) 

corrplot::corrplot(dfau_cor, method = "color",
                   outline = TRUE,
                   addgrid.col = "darkgray", cl.pos = "r", tl.col = "black",
                   tl.cex = 1, cl.cex = 1, type = "upper", bg="azure2",
                   diag = FALSE,
                   cl.ratio = 0.2,
                   cl.length = 5,
                   number.cex = 0.4)
print(dfau_cor)
```

### Análise de agrupamento hierárquico

```{r}
  da_pad<-decostand(  data_set_mult[-1] , 
                  method = "standardize",
                  na.rm=TRUE)
  labs <- data_set_mult |> pull(trat)
  da_pad_euc<-vegdist(da_pad,"euclidean") 
  da_pad_euc_ward<-hclust(da_pad_euc, method="ward.D")
  plot(da_pad_euc_ward,labels = labs,
     ylab="Distancia Euclidiana",
     xlab="Acessos", hang=-1,
     col="blue", las=1,
     cex=.6,lwd=1.5)
```
### Componentes principais

```{r}
pca <-  prcomp(da_pad,scale.=TRUE)
  # Autovalores
  eig<-pca$sdev^2
  print("==== Autovalores ====")
  print(round(eig,3))
  print("==== % da variância explicada ====")
  ve<-eig/sum(eig)
  print(round(ve,4))
  print("==== % da variância explicada acumulada ====")
  print(round(cumsum(ve),4)*100)
  print("==== Poder Discriminante ====")
  mcor<-cor(da_pad,pca$x)
  corrplot::corrplot(mcor)
  print("==== screeplot ====")
  screeplot(pca)
  abline(h=1)
  pc1V<-cor(da_pad,pca$x)[,1]/sd(cor(da_pad,pca$x)[,1])
  pc2V<-cor(da_pad,pca$x)[,2]/sd(cor(da_pad,pca$x)[,2])
  pc1c<-pca$x[,1]/sd(pca$x[,1])
  pc2c<-pca$x[,2]/sd(pca$x[,2])
  nv<-ncol(da_pad) # número de variáveis utilizadas na análise
  bip<-data.frame(pc1c,pc2c,labs)
  texto <- data.frame(
    x = pc1V,
    y = pc2V,
    # z = pc3V,
    label = names(da_pad)
  )
  
  print("==== Tabela da correlação dos atributos com cada PC ====")
  ck<-sum(pca$sdev^2>=0.98)
  tabelapca<-vector()
  for( l in 1:ck) tabelapca<-cbind(tabelapca,mcor[,l])
  colnames(tabelapca)<-paste(rep(c("PC"),ck),1:ck,sep="")
  pcat<-round(tabelapca,3)
  tabelapca<-tabelapca[order(abs(tabelapca[,1])),]
  
  
  bi_plot <- bip |>
    ggplot(aes(x=pc1c,y=pc2c,colour = as_factor(labs)))+
    geom_point() +
    theme_minimal() +
    # geom_text(aes(label = labs), vjust = -0.5, size = 3) +  # nomes dos tratamentos
    # # scale_shape_manual(values=16:18)+
    # # scale_color_manual(values=c("#009E73", "#999999","#D55E00")) +
    annotate(geom="text", x=pc1V, y=pc2V, label=names(pc1V),
              color="black",font=3) +
    geom_vline(aes(xintercept=0),
                color="black", size=1)+
    geom_hline(aes(yintercept=0),
                color="black", size=1) +
    annotate(geom="segment",
              x=rep(0,length(da_pad)),
              xend=texto$x,
              y=rep(0,length(da_pad)),
              yend=texto$y,color="black",lwd=.5) +
    geom_label(data=texto,aes(x=x,y=y,label=label),
               color="black",angle=0,fontface="bold",size=4,fill="white") +
    labs(x=paste("CP1 (",round(100*ve[1],2),"%)",sep=""),
         y=paste("CP2 (",round(100*ve[2],2),"%)",sep=""))+
    theme(legend.position = "top")
  
    print(bi_plot)
    print(tabelapca[,1:3])
```

